package com.person.newscopy.news.network;

public enum NewsType {
    All,//推荐
    HOT,//热点
    TECH,//科技
    WORLD,//国际
    POLITICS,//时政
    LOTTERY,//彩票
    SPORTS,//运动
    SOCIETY,//社会
    HOME,//家居
    INTERNET,//互联网
    SOFTWARE,//软件
    SMART_HOME,//智能家居
    ENTERTAINMENT,//娱乐
    MOVIE,//电影
    TELEPLAY,//电视剧
    SHOWS,//综艺
    GOSSIP,//八卦
    GAME,//游戏
    NBA,
    CAR,//汽车
    FINANCE,//财经
    STOCK,//股票
    FUNNY,//搞笑
    MILITARY,//军事
    BABY,//育儿
    FOOD,//美食
    FASHION,//时尚
    DISCOVERY,//探索
    REGIMEN,//养生
    HISTORY,//历史
    ESSAY,//美文
    TRAVEL,//旅行
    HOT_GALLERY,//热点图片
    OLD_PICTURE,//老照片
    GALLERY_PHOTOGRATHY,//摄影集
    OTHERS
}
