/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_person_newscopy_ndk_JavaUtil */

#ifndef _Included_com_person_newscopy_ndk_JavaUtil
#define _Included_com_person_newscopy_ndk_JavaUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_person_newscopy_ndk_JavaUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_person_newscopy_ndk_JavaUtil_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
